remote_theme: pages-themes/dinky@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one

title: 'Build-A-Large-Language-Model-From-Scratch'
description: 'Build A Large Language Model (From Scratch)'

show_downloads: false
