name: Dependabot-Manual

on:
  workflow_dispatch:
    inputs:
      package-ecosystem:
        description: 'Package ecosystem to check'
        required: true
        default: 'pip'
        type: choice
        options:
          - pip

jobs:
  dependabot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Dependabot
        uses: dependabot/fetch-metadata@v1.6.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable Dependabot
        run: gh api --method POST /repos/${{ github.repository }}/dependabot/scans
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}