name: Pylint

on:
  push:
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10", "3.11", "3.12", "3.13" ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pylint
      - name: Analysing the code with pylint
        run: |
          if [ -f .pylintrc ]; then
            echo "Using custom pylint configuration file: .pylintrc"
            pylint --rcfile=.pylintrc -j 0 $(git ls-files '*.py')
          else
            echo "No custom pylint configuration file found, using default settings."
            pylint -j 0 $(git ls-files '*.py')
          fi
